[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "file_ingestion"
version = "0.1.0"
dependencies = [
    "psycopg2-binary",
    "pandas",
    "python-dotenv",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["*"]